server:
  port: 9000

spring:
  application:
    name: cards

  datasource:
    url: jdbc:mysql://localhost:3309/cardsdb
    username: eazybank
    password: eazybank

  sql:
    init:
      mode: always

  jpa:
    show-sql: true

  config:
    import: optional:configserver:http://localhost:8071

  profiles:
    active: prod

management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true

  info:
    env:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: cards
    description: Cards application which is responsible for handling customer's cards related data
    version: 1.0.0

logging:
  level:
    com:
      ritam:
        cards: DEBUG

  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"