spring:

  application:
    name: configserver

  profiles:
    # active: native
    active: git

  cloud:
    config:
      server:
        # native:
        # search-locations: classpath:/config
        # search-locations: file:///C://Users//ritam//Documents//Config
        git:
          uri: https://github.com/ritamghosh97/eazybytes-config.git
          username: ritamghosh97
          password: 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
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    readiness-state:
      enabled: true

    liveness-state:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8071

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"